#!/bin/bash

############
# Written by David Gfeller, with help from TaeHyung Kim, Marc S. Tyndel for the logo visualization part with LoLa.
#
# For any question, please contact david.gfeller@unil.ch
#
# To cite MixMHCp, please refer to Bassani-Sternberg M and Gfeller D*, J. Immunol. (2016)
#
# MixMHCp can be used freely by academic groups for non-commercial purposes (see license).
# The product is provided free of charge, and, therefore, on an "as is"
# basis, without warranty of any kind.
#
# FOR-PROFIT USERS
# If you plan to use MixMHCp (version 1.1) in any for-profit
# application, you are required to obtain a separate license.
# To do so, please contact eauffarth@licr.org or lfoit@licr.org at the Ludwig Institute for  Cancer Research Ltd.
#
# Copyright (2016) David Gfeller
############


# Set the resource location. This has to be manually done on your machine
#lib_path="YOUR PATH TO MixMHCp1.1/lib FOLDER"
lib_path="/Users/davidgfeller/Research/LICR/Research/Immunopeptidomics/Full_package/MixMHCp1.1/source/MixMHCp1.1/lib/"


usage="Usage: MixMHCp -i INPUT -o OUTPUT -m MAX_MOTIFS"

###
if [ -f "$lib_path"/run_MixMHCp.pl ]; then
	lib=$lib_path
else
	echo MixMHCp not found.
	exit 1;
fi


if [[ "$1" == "--help" || "$1" == "-h" ]]; then
cat <<END
$usage
Mandatory parameters:
  -i, --input             Absolute or relative path to the input file (fasta format or list of peptides)
  -o, --output            Specify a location for the output


Optional parameters:
  -m, --max-pwms          Maximum number of PWMs (default: 6, max: 20)
  -b, --bias              Specific a residue bias file (default: none, U for uniprot based background frequencies, otherwise a file)
  -a, --alphabet          Specify your alphabet (default: ACDEFGHIKLMNPQRSTVWY, characters allowed: ACDEFGHIKLMNPQRSTVWYacdefghiklmnpqrstvwy)

Options:

  -k, --no-clean          Keep temporary files
  -l, --logo              Plot the logos
  -lt, --logo             Logo types (either LoLa or Seq2Logo)
  -n, --name              Name of the output (only showing in the html file)

END
	exit 0;
fi

# Defaults
output=./
maxpwms=6

logo=1

# Parse flags
while [ $# -gt 0 ]; do
	case $1 in
		-i | --input) input=$2; shift 2;;
		-o | --output) output=$2; shift 2;;
		-m | --max-pwms) maxpwms=$2; shift 2;;
		-a | --alphabet) alphabet=$2; shift 2;;
		-k | --no-clean) noclean=-tm; shift 1;;
		-b | --bias) bias=$2; shift 2;;
		-l | --logo) logo=$2; shift 2;;
		-lt | --logo_type) logo_type=$2; shift 2;;
		-n | --name) name=$2; shift 2;;
		*) shift 1;;
	esac
done

# Check for mandatory parameters
if	! [[ -n "$input" ]]; then 
	echo Try: "musi --help"
	echo $usage;
	exit 1;
fi

if [ -n "$bias" ]; then
	bias_file="-b $bias";
else
    bias_file="-b 0";
fi
    

if [ -n "$name" ]; then
    name_file="-n $name";
else
    name_file="-n Peptides";
fi

if [ -n "$alphabet" ]; then
    alphabet_command="-al $alphabet";
else
    alphabet_command="-al ACDEFGHIKLMNPQRSTVWY";
fi

if [ -n "$logo_type" ]; then
    logo_type_command="-lt $logo_type";
else
    logo_type_command="-lt LoLa";
fi


input=`perl -e 'use Cwd "abs_path";print abs_path(shift)' $input`;

if [ -f "$input" ]; then
	input="-i $input";
else
	echo Input file does not appear to exist.
	exit 1;
fi


mkdir -p $output
output=`perl -e 'use Cwd "abs_path";print abs_path(shift)' $output`;
output=$output/

lib_dir=`perl -e 'use Cwd "abs_path";print abs_path(shift)' $lib`/

perl $lib_dir/run_MixMHCp.pl $lib_dir $noclean -m $maxpwms $bias_file $input -o $output -l $logo $name_file $logo_type_command $alphabet_command

